ExcelParser/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('document_manager.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

document_manager/models.py
import json
import os
from abc import abstractmethod
import datetime

from django.conf import settings
from django.core.exceptions import FieldError
from django.db import models
from django.urls import reverse
from django.utils.timezone import now

from document_manager.services.dataframes_services import ParserToDatabase
from document_manager.validators import validate_file_extension
from plot_engine.json_manager import generate_sample, upload_data


class DocumentAbstract:
    """
    Интерфейс модели Document
    """

    @abstractmethod
    def get_file_path(self):
        pass

    @abstractmethod
    def get_title(self):
        pass

    @abstractmethod
    def get_content(self):
        pass


class Event(models.Model):
    """
    Событие - начало подстчета баллов
    """
    title = models.CharField('Название мероприятия', max_length=150, unique=True)

    outdated = models.BooleanField('Доступно в истории просмотров', default=False)
    current = models.BooleanField('Текущее', default=True)

    day = models.PositiveSmallIntegerField('День')
    month = models.PositiveSmallIntegerField('Месяц')
    year = models.PositiveSmallIntegerField('Год')
    mvr_table_url = models.CharField(max_length=255, null=True, blank=True, verbose_name='Ссылка на таблицу (МВР)')
    mvr_form_url = models.CharField(max_length=255, null=True, blank=True, verbose_name='Ссылка на форму (МВР)')
    sheet_rules = models.TextField(verbose_name='Листы Excel файла',
                                   help_text='<Название листа1>;<Название листа2>;...', null=True)

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'Событие'

    def get_absolute_url(self):
        return reverse("documents_event_slug", kwargs={"slug": self.title})

    def __str__(self):
        return f'{self.title}'

    def get_start_date(self) -> datetime:
        return datetime.date(year=self.year, month=self.month, day=self.day)


class Document(DocumentAbstract, models.Model):
    """
    Модель документа
    """
    title = models.CharField('Название', max_length=200)
    uploaded_file = models.FileField('Файл', upload_to="media/", validators=[validate_file_extension, ])
    date_time_of_added = models.DateTimeField('Время добавления', auto_now=True)
    date_time_of_updated = models.DateTimeField('Время обновления', blank=True, null=True)
    content = models.TextField('Содержание', blank=True)

    deadline_ratio = models.IntegerField('Дедлайн', blank=True, null=True)
    status_ratio = models.IntegerField('Статус', blank=True, null=True)
    action_plan_ratio = models.IntegerField('План действий', blank=True, null=True)

    password = models.CharField('Пароль', max_length=150)
    json_file_path = models.CharField('json', max_length=250, blank=True)

    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)

    _file_json = None

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документ'

    def __init__(self, *args, **kwargs):
        super(Document, self).__init__(*args, **kwargs)
        self._file_json = self.get_file_json()

    def get_file_path(self):
        if self.uploaded_file.path:
            return f"{self.uploaded_file.path}"

        return self.uploaded_file.url

    def get_replace_filepath_json(self):
        # TODO убрал /code/ при переносе сервера временно
        file_path = self.json_file_path

        file_path = file_path.replace('/code/', '/', 1)

        if file_path:
            file_path = f'{file_path}'

        if os.path.exists(file_path):
            return file_path
        elif os.path.exists(f"{settings.BASE_DIR}{file_path}"):
            return f"{settings.BASE_DIR}{file_path}"

        return file_path

    def get_file_json(self):
        if self._file_json:

            return self._file_json

        file_path = self.get_replace_filepath_json()

        if file_path:
            try:
                with open(file_path) as f:
                    return json.load(f, )
            except IsADirectoryError:
                return {}
        return {}

    def last_deadline_count(self):
        return int(self.get_file_json()['y2'][-1])

    def last_status_count(self):
        return int(self.get_file_json()['y1'][-1])

    def last_action_count(self):
        return int(self.get_file_json()['y3'][-1])

    def deadline_changed_ratio(self):
        data = self.get_file_json()
        is_changed = len(data['y2']) > 2
        if is_changed:
            prev_deadline = data['y2'][-2]
            return int(data['y2'][-1]) - int(prev_deadline)
        return 0

    def status_changed_ratio(self):
        data = self.get_file_json()
        is_changed = len(data['y1']) > 2
        if is_changed:
            prev_status = data['y1'][len(data['y1']) - 2]
            return int(data['y1'][-1]) - int(prev_status)
        return 0

    def action_changed_ratio(self):
        data = self.get_file_json()
        is_changed = len(data['y3']) > 2
        if is_changed:
            prev_action = data['y3'][len(data['y3']) - 2]
            return int(data['y3'][-1]) - int(prev_action)
        return 0

    def get_title(self):
        return f"{self.title}"

    def get_content(self):
        return f"{self.content}"

    def save(self, *args, **kwargs):
        """
        Сохранение в БД значений суммарных очков  после парсинга документа
        """

        if not self.uploaded_file:
            raise FieldError('Не передан файл')
        if validate_file_extension(self.uploaded_file):
            super().save(*args, **kwargs)
        try:
            pars = ParserToDatabase(self).get_total_values()
            self.content = 'Content'
            self.deadline_ratio = abs(pars.get('deadline', 0) // 10)
            self.status_ratio = pars.get('status', 0)
            self.action_plan_ratio = pars.get('task', 0)
            self.date_time_of_updated = now()
        except:
            self.delete()
            raise FieldError('Некорректный файл')

        if self.json_file_path:
            self.json_file_path = self.json_file_path
        else:
            self.json_file_path = generate_sample()

        upload_data(
            file=self.json_file_path,
            time_delta=self.date_time_of_updated.date(),
            status_value=self.status_ratio,
            deadline_value=self.deadline_ratio // 10,
            plan_value=self.action_plan_ratio
        )

        return super(Document, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.title}"

templates/documents/document_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row" style="margin-top: 14px;">
        <div class="col-lg-2"></div>
        <div class="col-lg-10">
            <div class="breadcrumb ">
                <a href="/">Главная</a>/
                <a href="{% url 'documents_event_slug' document.event.title %}">{{ document.event.title }}</a>/
                <a href="#">{{ document.title }}</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2">
            <ul class="sidebar-menu">
                <a class="menu-link" href="#" data-bs-toggle="modal" data-bs-target="#updateModal">
                    <li class="menu-item justify-content-center justify-content-lg-start">
                        <div class="menu-icon"><span class="_icon-update"></span></div>
                        <div>Обновить проект</div>
                    </li>
                </a>
                <a class="menu-link" href="{% url 'download' document.pk %}">
                    <li class="menu-item justify-content-center justify-content-lg-start">
                        <div class="menu-icon"><span class="_icon-download"></span></div>
                        <div>Скачать файл</div>
                    </li>
                </a>
            </ul>
            {% if request.user.is_authenticated and request.user.is_superuser %}
                <hr>
                <ul class="admin-sidebar justify-content-center justify-content-lg-start mb-3">
                    <a href="{% url 'delete' document.pk %}" class="admin-link">
                        <li>Удалить проект</li>
                    </a>
                </ul>
            {% endif %}
        </div>
        <div class="col-lg-10">
            <div class="project-detail">
                <div class="common-block project-detail-info" style="padding-top: 40px;">
                    <div class="row" style="margin-bottom: 30px;">
                        <div class="col-lg-4 text-center">
                            <div class="project-img">
                                <img src="{% static '/img/project_empty.svg' %}" alt="" width="120" height="120">
                            </div>
                            <div class="project-title">{{ document.title }}</div>
                        </div>
                        <div class="col-lg-8">
                            <div class="row">
                                <div class="col-lg-4 text-center text-lg-start mt-3 mt-lg-0">
                                    <div class="project-info-title mb-3 mb-lg-5">
                                        Статус
                                    </div>
                                    <div class="project-info-value justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                                        <div class="value-ratio">
                                            {{ document.status_ratio }}
                                        </div>
                                        {% if document.status_changed_ratio == 0 %}
                                            <div class="project-value-changed neutral-value">
                                                +{{ document.status_changed_ratio }}</div>
                                        {% elif document.status_changed_ratio > 0 %}
                                            <div class="project-value-changed positive-value">
                                                +{{ document.status_changed_ratio }}</div>
                                        {% else %}
                                            <div class="project-value-changed negative-value">{{ document.status_changed_ratio }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-lg-4 text-center text-lg-start">
                                    <div class="project-info-title mb-3 mb-lg-5">
                                        Дедлайн
                                    </div>
                                    <div class="project-info-value justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                                        <div class="value-ratio">{{ document.deadline_ratio }}</div>
                                        {% if document.deadline_changed_ratio == 0 %}
                                            <div class="project-value-changed neutral-value">
                                                +{{ document.deadline_changed_ratio }}</div>
                                        {% elif document.deadline_changed_ratio >= 0 %}
                                            <div class="project-value-changed positive-value">
                                                +{{ document.deadline_changed_ratio }}</div>
                                        {% else %}
                                            <div class="project-value-changed negative-value">{{ document.deadline_changed_ratio }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="col-lg-4 text-center text-lg-start">
                                    <div class="project-info-title mb-3 mb-lg-5">
                                        План
                                    </div>
                                    <div class="project-info-value justify-content-center justify-content-lg-start mb-3 mb-lg-0">
                                        <div class="value-ratio">{{ document.action_plan_ratio }}</div>
                                        {% if document.action_changed_ratio == 0 %}
                                            <div class="project-value-changed neutral-value">
                                                +{{ document.action_changed_ratio }}</div>
                                        {% elif document.action_changed_ratio > 0 %}
                                            <div class="project-value-changed positive-value">
                                                +{{ document.action_changed_ratio }}</div>
                                        {% else %}
                                            <div class="project-value-changed negative-value">{{ document.action_changed_ratio }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <span class="c-secondary">Последнее обновление {{ document.date_time_of_updated }}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="project-graph">
                <div class="common-block project-graph-detail">
                    <div class="project-graph-title text-center"><span>График изменения проекта</span></div>
                    <div class="project-graph-colors" id="legend-colors">
                        <ul id="project-chart-legend"></ul>
                        {#                        <li class="color text-center">#}
                        {#                            <div class="project-graph-color" style="background: #ED9C87;"></div>#}
                        {#                            <div class="color-title">Статус</div>#}
                        {#                        </li>#}
                        {#                        <li class="color text-center">#}
                        {#                            <div class="project-graph-color" style="background: #FECA7E;"></div>#}
                        {#                            <div class="color-title">Дедлайн</div>#}
                        {#                        </li>#}
                    </div>
                    {#                    <div id="chart"></div>#}
                    <div class="project-graph">
                        <canvas id="project-chart" height="150"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#    <div class="d-flex" style="margin-top: 10px;">#}
    {##}
    {#        <div>#}
    {#            <div>#}
    {##}
    {#                <a title="Скачать" style="padding-right: 2px; text-decoration:None"#}
    {#                   href="{% url 'download' document.pk %}">#}
    {#                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor"#}
    {#                         class="bi bi-arrow-down-square" viewBox="0 0 16 16">#}
    {#                        <path fill-rule="evenodd"#}
    {#                              d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm8.5 2.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>#}
    {#                    </svg>#}
    {#                </a>#}
    {#                <span>{{ document.title }}</span>#}
    {#                <span>Последнее обновление: {{ document.date_time_of_updated }}</span>#}
    {##}
    {##}
    {#            </div>#}
    {#        </div>#}
    {##}
    {#        <div>#}
    {#        </div>#}
    {#    </div>#}
    {% include 'includes/modals/update_project_modal.html' %}
{% endblock %}

{% block js_block %}
    <script src="{% static 'includes/chartjs/chart.js' %}"></script>
    <script>
        let projectData ={{ data|safe }};
    </script>
    <script src="{% static 'js/project_detail.js' %}"></script>
{% endblock %}

templates/documents/document_history.html
{% extends 'base.html' %}
{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="{% static 'includes/datatable/css/jquery.dataTables.min.css' %}">
    <script src="{% static 'includes/datatable/js/jquery.dataTables.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row" style="margin-top: 14px; padding: 0 75px">
        <div class="col-lg-12">
            <div class="breadcrumb ">
                <a href="/">Главная</a>/
                <a href="#">История проектов</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="accordion" id="accordionHistoryProjects">
                {% for event in events %}
                    <div class="accordion-custom-item">
                        <div class="accordion-custom-header" id="heading{{ forloop.counter }}">
                            <button class="accordion-custom-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapse{{ forloop.counter }}"
                                    aria-expanded="true" aria-controls="collapseOne">
                                {{ event.title }}
                            </button>
                        </div>
                        <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse"
                             aria-labelledby="headingOne"
                             data-bs-parent="#accordionHistoryProjects">
                            <div class="accordion-body accordion-custom-body">
                                <div class="table-responsive">
                                    <table class="history-document-table w-100"
                                           id="history-table-{{ forloop.counter }}"
                                           data-table-type="paginate-table-{{ forloop.counter }}">
                                        <thead>
                                        <th class="c-secondary">№</th>
                                        <th class="c-secondary">Название</th>
                                        <th class="c-secondary text-center">Рейтинг по статусу</th>
                                        <th class="c-secondary text-center">Рейтинг по дедлайну</th>
                                        <th class="c-secondary text-center">Рейтинг по плану</th>
                                        </thead>
                                        <tbody>
                                        {% for document in event.document_set.all %}
                                            <tr onclick="location.href='{% url 'document' document.pk %}'">
                                                <td scope="row" class="c-secondary"
                                                    style="margin-bottom: 19px; padding: 8px;">{{ forloop.counter }}</td>
                                                <td class="history-td">
                                                    {{ document.title }}
                                                </td>
                                                <td class="history-td" align="center">{{ document.status_ratio }}</td>
                                                <td class="history-td" align="center">{{ document.deadline_ratio }}</td>
                                                <td class="history-td"
                                                    align="center">{{ document.action_plan_ratio }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


    {#    <div class="accordion" id="accordionHistoryProjects">#}
    {#        {% for event in events %}#}
    {#            <div class="accordion-item">#}
    {#            <h2 class="accordion-header" id="accordion{{event.pk}}">#}
    {#                <button class="accordion-button" type="button" data-bs-toggle="collapse"#}
    {#                        data-bs-target="#collapse{{event.pk}}"#}
    {#                        aria-expanded="true" aria-controls="collapseOne">#}
    {#                    {{event.title}}#}
    {#                </button>#}
    {#            </h2>#}
    {#            <div id="collapse{{event.pk}}" class="accordion-collapse collapse show" aria-labelledby="headingOne"#}
    {#                 data-bs-parent="accordion{{event.pk}}">#}
    {#                <div class="accordion-body">#}
    {##}
    {#                    <div class="table-responsive">#}
    {#                        <table class="table table-hover">#}
    {#                            <thead>#}
    {#                            <tr>#}
    {#                                <th scope="col">#</th>#}
    {#                                <th scope="col">Название</th>#}
    {#                                <th scope="col">#}
    {#                                    <div class="d-flex">#}
    {#                                        <span>Рейтинг по статусу</span>#}
    {#                                    </div>#}
    {##}
    {#                                </th>#}
    {#                                <th scope="col">#}
    {##}
    {#                                    <div class="d-flex">#}
    {#                                        <span>Рейтинг по дедлайну</span>#}
    {#                                    </div>#}
    {##}
    {#                                </th>#}
    {#                                <th scope="col">#}
    {##}
    {#                                    <div class="d-flex">#}
    {#                                        <span>Рейтинг по составленному плану</span>#}
    {#                                    </div>#}
    {#                                </th>#}
    {#                                <th scope="col"></th>#}
    {#                            </tr>#}
    {#                            </thead>#}
    {#                            <tbody>#}
    {#                            {% for d in event.document_set.all %}#}
    {#                            <tr>#}
    {#                                <th scope="row">{{ forloop.counter }}</th>#}
    {#                                <td><a href="{% url 'document' d.pk %}" style="text-decoration:None">{{ d.title }}</a>#}
    {#                                </td>#}
    {#                                <td>{{ d.status_ratio }}</td>#}
    {#                                <td>{{ d.deadline_ratio }}</td>#}
    {#                                <td>{{ d.action_plan_ratio }}</td>#}
    {#                                <td>#}
    {# Скачать файл #}
    {#                                    <a title="Скачать" style="padding-right: 2px; text-decoration:None"#}
    {#                                       href="{% url 'download' d.pk %}">#}
    {#                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"#}
    {#                                             fill="currentColor"#}
    {#                                             class="bi bi-arrow-down-circle" viewBox="0 0 16 16">#}
    {#                                            <path fill-rule="evenodd"#}
    {#                                                  d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>#}
    {#                                        </svg>#}
    {#                                    </a>#}
    {##}
    {#                                    <div class="modal fade" id="myModal{{ d.pk }}">#}
    {#                                        <div class="modal-dialog">#}
    {#                                            <div class="modal-content">#}
    {##}
    {#                                                <!-- Modal Header -->#}
    {#                                                <div class="modal-header">#}
    {#                                                    <h4 class="modal-title">Обновление файла</h4>#}
    {#                                                    <button type="button" class="btn-close"#}
    {#                                                            data-bs-dismiss="modal"></button>#}
    {#                                                </div>#}
    {##}
    {#                                                <!-- Modal body -->#}
    {#                                                <div class="modal-body d-flex">#}
    {#                                                    <form class="d-flex" action="{% url 'update' d.pk %}" method="post"#}
    {#                                                          enctype="multipart/form-data">#}
    {#                                                        {% csrf_token %}#}
    {#                                                        <div>#}
    {##}
    {##}
    {#                                                            {{ formDocUpdate.as_p }}#}
    {#                                                        </div>#}
    {##}
    {#                                                        <div>#}
    {#                                                            <input type="submit" value="Загрузить"#}
    {#                                                                   class="btn btn-success">#}
    {#                                                        </div>#}
    {##}
    {##}
    {#                                                    </form>#}
    {#                                                </div>#}
    {##}
    {#                                                <!-- Modal footer -->#}
    {#                                                <div class="modal-footer">#}
    {#                                                    <button type="button" class="btn btn-danger"#}
    {#                                                            data-bs-dismiss="modal">Закрыть#}
    {#                                                    </button>#}
    {#                                                </div>#}
    {##}
    {#                                            </div>#}
    {#                                        </div>#}
    {#                                    </div>#}
    {# Удалить файл ( для админа ) #}
    {#                                    {% if request.user.is_staff %}#}
    {#                                    <a title="Удалить файл" href="{% url 'delete' d.pk %}" style="text-decoration:None">#}
    {#                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"#}
    {#                                             fill="currentColor"#}
    {#                                             class="bi bi-basket3" viewBox="0 0 16 16">#}
    {#                                            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>#}
    {#                                        </svg>#}
    {#                                    </a>#}
    {#                                    {% endif %}#}
    {#                                </td>#}
    {##}
    {##}
    {#                            </tr>#}
    {##}
    {#                            {%endfor%}#}
    {#                            </tbody>#}
    {#                        </table>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#        {% endfor %}#}
    {#    </div>#}
{% endblock %}

{% block js_block %}
    <script src="{% static 'js/paginate_table.js' %}"></script>
{#    <script>#}
{#        jQuery(document).ready(function () {#}
{#            $tables = new DataTable('table[id^=history-table-]', {#}
{#                dom: 't<"d-flex justify-content-center"p>',#}
{#                ordering: false,#}
{#                pageLength: 5,#}
{#                language: {#}
{#                    oPaginate: {#}
{#                        sNext: '<div class="d-flex align-content-center justify-content-center"><span class="svg-arrow i-left"></span></div>',#}
{#                        sPrevious: '<div class="d-flex align-content-center justify-content-center"><span class="svg-arrow i-right"></span></div>',#}
                        {#sFirst: '<i class="fa fa-step-backward"></i>',#}
                        {#sLast: '<i class="fa fa-step-forward"></i>'#}
{#                    }#}
{#                }#}
{#            });#}
{#            console.log($tables);#}
{#        });#}
{#    </script>#}
{% endblock %}

templates/documents/message.html
{% extends 'base.html' %}

{% block header %}

{%endblock header%}

{% block content %}


    {{ message }}
{% endblock %}